/**
 * control_center
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Poste from './model/Poste';
import User from './model/User';
import HealthApi from './api/HealthApi';
import LoginApi from './api/LoginApi';
import PostesApi from './api/PostesApi';


/**
* Api de ControlCenter.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var ControlCenterApi = require('index'); // See note below*.
* var xxxSvc = new ControlCenterApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new ControlCenterApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new ControlCenterApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new ControlCenterApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Poste model constructor.
     * @property {module:model/Poste}
     */
    Poste,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
    * The HealthApi service constructor.
    * @property {module:api/HealthApi}
    */
    HealthApi,

    /**
    * The LoginApi service constructor.
    * @property {module:api/LoginApi}
    */
    LoginApi,

    /**
    * The PostesApi service constructor.
    * @property {module:api/PostesApi}
    */
    PostesApi
};
