openapi: 3.0.0
info:
  version: '0.0.1'
  title: 'CommandProtocol'
servers:
  - url: 'localhost:8080'
paths:
    /alive:
        get:
            operationId: checkAlive
            security: []
            responses:
                '200':
                    description: Alive
                    content:
                        text/plain:
                            schema:
                                type: string
                                pattern: "^salut$"

    /auth/login:
        post:
            operationId: login
            security: []
            requestBody:
                description: The user form to login
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#components/schemas/LoginForm'
            responses:
                '200':
                    description: OK
                    content: 
                        application/jwt:
                            schema:
                                type: string
                '401':
                    $ref: '#components/responses/Unauthorized'
    /postes:
        get:
            operationId: listPostes
            responses:
                '200':
                    description: Liste des postes
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#components/schemas/Poste'

components:
    schemas:
        LoginForm:
            type: object
            properties:
                username:
                    type: string
                password:
                    type: string
                    format: password
            required:
                - username
                - passsword
        Poste:
            type: object
            properties:
                is_on:
                    type: boolean
                is_compromised:
                    type: boolean
                os:
                    type: string
                hostname:
                    type: string
                ip:
                    type: string
    responses:
        Unauthorized:
            description: Access token is missing or invalid
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT
        
security:
  - bearerAuth: []
