/**
 * control_center
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LoginForm model module.
 * @module model/LoginForm
 * @version 0.1.0
 */
class LoginForm {
    /**
     * Constructs a new <code>LoginForm</code>.
     * @alias module:model/LoginForm
     * @param username {String} 
     * @param password {String} 
     */
    constructor(username, password) { 
        
        LoginForm.initialize(this, username, password);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, username, password) { 
        obj['username'] = username;
        obj['password'] = password;
    }

    /**
     * Constructs a <code>LoginForm</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LoginForm} obj Optional instance to populate.
     * @return {module:model/LoginForm} The populated <code>LoginForm</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LoginForm();

            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} username
 */
LoginForm.prototype['username'] = undefined;

/**
 * @member {String} password
 */
LoginForm.prototype['password'] = undefined;






export default LoginForm;

