/**
 * control_center
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Poste model module.
 * @module model/Poste
 * @version 0.1.0
 */
class Poste {
    /**
     * @member {Boolean} is_on
     * @type {Boolean}
     */
    is_on;
    /**
     * @member {Boolean} is_compromised
     * @type {Boolean}
     */
    is_compromised;
    /**
     * @member {String} os
     * @type {String}
     */
    os;
    /**
     * @member {String} hostname
     * @type {String}
     */
    hostname;
    /**
     * @member {String} ip
     * @type {String}
     */
    ip;

    

    /**
     * Constructs a new <code>Poste</code>.
     * @alias module:model/Poste
     * @param isOn {Boolean} 
     * @param isCompromised {Boolean} 
     * @param os {String} 
     * @param hostname {String} 
     * @param ip {String} 
     */
    constructor(isOn, isCompromised, os, hostname, ip) { 
        
        Poste.initialize(this, isOn, isCompromised, os, hostname, ip);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, isOn, isCompromised, os, hostname, ip) { 
        obj['is_on'] = isOn;
        obj['is_compromised'] = isCompromised;
        obj['os'] = os;
        obj['hostname'] = hostname;
        obj['ip'] = ip;
    }

    /**
     * Constructs a <code>Poste</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Poste} obj Optional instance to populate.
     * @return {module:model/Poste} The populated <code>Poste</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Poste();

            if (data.hasOwnProperty('is_on')) {
                obj['is_on'] = ApiClient.convertToType(data['is_on'], 'Boolean');
            }
            if (data.hasOwnProperty('is_compromised')) {
                obj['is_compromised'] = ApiClient.convertToType(data['is_compromised'], 'Boolean');
            }
            if (data.hasOwnProperty('os')) {
                obj['os'] = ApiClient.convertToType(data['os'], 'String');
            }
            if (data.hasOwnProperty('hostname')) {
                obj['hostname'] = ApiClient.convertToType(data['hostname'], 'String');
            }
            if (data.hasOwnProperty('ip')) {
                obj['ip'] = ApiClient.convertToType(data['ip'], 'String');
            }
        }
        return obj;
    }
}



export default Poste;

